[bundle]
output = "c-plugins.so"

[[plugins]]
source = "./file-logger"

[[plugins]]
source = "./access-control"

[[plugins]]
source = "./byte-counter"

[[plugins]]
source = "./content-filter"

[[plugins]]
source = "./text-transform"

[[plugins]]
source = "./exec-logger"

[[plugins]]
source = "./net-logger"

[[plugins]]
source = "./net-transform"

[[plugins]]
source = "./http-logger"

[[plugins]]
source = "./http-rewrite"
